
```{r setup}
#| include: false
options(scipen = 100)
library(tidyverse)
library(tidymodels)
library(ranger)
library(rsample)
library(rlang)
```

```{r}
set.seed(100)
iris_split <- initial_split(iris, prop = 1/3)

iris_split
```


```{r}
model <- ranger(Species ~ ., data = training(iris_split), probability = TRUE)
```

```{r}
preds <- predict(model, testing(iris_split))

tbl_iris <- testing(iris_split) %>% 
  bind_cols(preds$predictions)

glimpse(tbl_iris)
```


```{r}
tbl_iris %>% 
  ungroup() %>% 
  arrange(virginica) %>% 
  mutate(is_virginica = ifelse(Species == "virginica", 1, 0)) %>% 
  select(virginica, is_virginica) %>% 
  mutate(
    per = cumsum(is_virginica) / sum(is_virginica), 
    accum_prob = cummean(virginica), 
    accum_positives = cummean(per)
  )
```

```{r}
tbl_iris %>% 
  ungroup() %>% 
  arrange(virginica) %>% 
  mutate(is_virginica = ifelse(Species == "virginica", 1, 0)) %>% 
  select(virginica, is_virginica) %>% 
  mutate(
    per = cumsum(is_virginica) / sum(is_virginica), 
    accum_prob = cumsum(virginica), 
    accum_positives = cumsum(per),
    accum_two = cumsum(is_virginica)
  )%>% 
  ggplot() +
  geom_line(aes(accum_prob, accum_two)) +
  geom_line(aes(accum_two, accum_two), linetype = 2)
```

```{r}
tbl_iris %>% 
  ungroup() %>% 
  arrange(virginica) %>% 
  mutate(is_virginica = ifelse(Species == "virginica", 1, 0)) %>% 
  select(virginica, is_virginica) %>% 
  mutate(
    per = cumsum(is_virginica) / sum(is_virginica), 
    accum_prob = cumsum(virginica), 
    accum_positives = cumsum(per),
    accum_two = cumsum(is_virginica)
  )%>% 
  ggplot() +
  geom_line(aes(accum_prob, accum_two)) +
  geom_line(aes(accum_two, accum_two), linetype = 2)
```

```{r}
tbl_iris %>% 
  ungroup() %>% 
  arrange(setosa) %>% 
  mutate(is_setosa = ifelse(Species == "setosa", 1, 0)) %>% 
  select(setosa, is_setosa) %>% 
  mutate(
    per = cumsum(is_setosa) / sum(is_setosa), 
    accum_prob = cumsum(setosa), 
    accum_positives = cumsum(per),
    accum_two = cumsum(is_setosa)
  ) %>% 
  ggplot() +
  geom_line(aes(accum_prob, accum_two)) +
  geom_line(aes(accum_two, accum_two), linetype = 2)
```



```{r}
tbl_iris %>% 
  ungroup() %>% 
  arrange(versicolor) %>% 
  mutate(is_versicolor = ifelse(Species == "versicolor", 1, 0)) %>% 
  select(versicolor, is_versicolor) %>% 
  mutate(
    per = cumsum(is_versicolor) / sum(is_versicolor), 
    accum_prob = cumsum(versicolor), 
    accum_positives = cumsum(per), 
    accum_two = cumsum(is_versicolor),
    ratio = accum_positives / accum_prob
  ) %>% 
  ggplot() +
  geom_line(aes(accum_prob, accum_positives)) +
  geom_line(aes(accum_two, accum_positives), linetype = 2)
```
```{r}
iris %>% 
  count(Species)
```


```{r}
tibble(x = sample(c(0,1), 1000, replace = TRUE, prob = c(0.66, 0.33))) %>% 
  arrange(x) %>% 
  mutate(
    y = cumsum(x) / sum(x),
    y2 = cummean(y),
    y3 = cummean(x),
    ratio = y2 / y3
    )
```

```{r}
tibble(x = sample(c(0,1), 1000, replace = TRUE, prob = c(0.66, 0.33))) %>% 
  arrange(x) %>% 
  mutate(
    y = cumsum(x) / sum(x),
    y2 = cummean(y),
    y3 = cummean(x),
    ratio = y2 / y3
    ) 
```

```{r}
tbl_iris %>% 
  ungroup() %>% 
  arrange(versicolor) %>% 
  mutate(is_versicolor = ifelse(Species == "versicolor", 1, 0)) %>% 
  select(versicolor, is_versicolor) %>% 
  mutate(
    prob_sum = cummean(versicolor), 
    is_sum = cumsum(is_versicolor),
    test = cummean(is_versicolor)
  ) %>% 
  ggplot() + 
  geom_line(aes(prob_sum, test)) +
  geom_line(aes(test, test), linetype = 3)
```


```{r}
tbl_iris %>% 
  ungroup() %>% 
  arrange(versicolor) %>% 
  mutate(is_versicolor = ifelse(Species == "versicolor", 1, 0)) %>% 
  select(versicolor, is_versicolor) %>% 
  mutate(
    prob_sum = cummean(versicolor),
    is_sum = cummean(is_versicolor)
  )

```

