FROM rstudio/r-session-complete:jammy
RUN /opt/R/R-$R_VERSION/bin/R -e  'install.packages("tidyverse", repos="https://packagemanager.rstudio.com/cran/__linux__/jammy/latest")' 


# docker run -it 31b9e06b7fab /bin/bash
